version: "3"

services:
    app:
        # image: nvcr.io/nvidia/pytorch:21.04-py3
        image: jetson-dev:latest
        restart: always
        # ports:
        #     - "8080:80" # exposing port 80 of image server to port 8080 of host server
        volumes:
            - ./:/workspace
            - /tmp/.X11-unix/:/tmp/.X11-unix

        environment: 
            - DISPLAY=$DISPLAY
        # devices: 
        #     - /dev/video0
        # network_mode: host
        
        # code below down to capabilities is equivalent of --gpus all
        deploy:
            resources:
              reservations:
                devices:
                - capabilities: [gpu]

        # 2 line sbelow open docker in interactive mode
        stdin_open: true   # docker run -i
        tty: true   # docker run -t

        # can't explain why I need these
        privileged: true   
        # ipc: host
        
        